// //! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

// use sea_orm::entity::prelude::*;

// #[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
// #[sea_orm(table_name = "config")]
// pub struct Model {
//     #[sea_orm(primary_key, auto_increment = false)]
//     pub id: Option<i32>,
//     pub smtp_username: Option<String>,
//     pub smtp_password: Option<String>,
// }

// #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
// pub enum Relation {}

// impl ActiveModelBehavior for ActiveModel {}
